imports:
    - { resource: parameters.yml }
security:
    encoders:
        SonodigestBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10       
    role_hierarchy:
#        ROLE_MEDICO:   ROLE_USER 
#        ROLE_ADMIN:    [ROLE_MEDICO, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:      
        user_login:
            entity: { class: SonodigestBundle\Entity\Usuario, property: username }
        
    firewalls:
        #Firewalls para ingreso de la Plus belle
        login_:
            pattern:  ^/secured/login$
            security: false
            anonymous: ~
        secured_area_:
            pattern: ^/
            switch_user: { role: ROLE_ADMIN, parameter: _change }
            form_login:
                login_path: /secured/login
                check_path: /secured/login_check
                default_target_path: /admin/panel
                #always_use_default_target_path: true 
                failure_path:      /secured/login
                #use_referer:         true
            logout:
                path: /secured/logout
                target: /secured/login
            anonymous: ~        
    access_control:
        - { path: ^/admin/*, role:  ROLE_USER } 
        - { path: ^/secured/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #Roles admin
        - { path: ^/admin/*, role:  ROLE_ADMIN } 
        #Roles medicos
        #- { path: ^/*, role:  ROLE_MEDICOS } 
        #Roles usuarios
        #- { path: ^/*, role:  ROLE_USER } 
        #- { path: ^/inicio, role: IS_AUTHENTICATED_ANONYMOUSLY }